# CMake generated Testfile for 
# Source directory: /home/soniar/naiveDarknetNNPACKARMSVE/NNPACK
# Build directory: /home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/build1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(convolution-inference-smoketest "convolution-inference-smoketest")
set_tests_properties(convolution-inference-smoketest PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;580;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-inference-alexnet "convolution-inference-alexnet-test")
set_tests_properties(convolution-inference-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;586;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-inference-overfeat "convolution-inference-overfeat-test")
set_tests_properties(convolution-inference-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;592;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-inference-vgg "convolution-inference-vgg-test")
set_tests_properties(convolution-inference-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;598;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-output-smoketest "convolution-output-smoketest")
set_tests_properties(convolution-output-smoketest PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;605;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-output-alexnet "convolution-output-alexnet-test")
set_tests_properties(convolution-output-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;611;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-output-overfeat "convolution-output-overfeat-test")
set_tests_properties(convolution-output-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;617;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-output-vgg "convolution-output-vgg-test")
set_tests_properties(convolution-output-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;623;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-input-gradient-smoketest "convolution-input-gradient-smoketest")
set_tests_properties(convolution-input-gradient-smoketest PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;629;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-input-gradient-alexnet "convolution-input-gradient-alexnet-test")
set_tests_properties(convolution-input-gradient-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;635;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-input-gradient-overfeat "convolution-input-gradient-overfeat-test")
set_tests_properties(convolution-input-gradient-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;641;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-input-gradient-vgg "convolution-input-gradient-vgg-test")
set_tests_properties(convolution-input-gradient-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;647;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-kernel-gradient-smoketest "convolution-kernel-gradient-smoketest")
set_tests_properties(convolution-kernel-gradient-smoketest PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;653;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-kernel-gradient-alexnet "convolution-kernel-gradient-alexnet-test")
set_tests_properties(convolution-kernel-gradient-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;659;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-kernel-gradient-overfeat "convolution-kernel-gradient-overfeat-test")
set_tests_properties(convolution-kernel-gradient-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;665;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(convolution-kernel-gradient-vgg "convolution-kernel-gradient-vgg-test")
set_tests_properties(convolution-kernel-gradient-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;671;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(fully-connected-inference-alexnet "fully-connected-inference-alexnet-test")
set_tests_properties(fully-connected-inference-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;679;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(fully-connected-inference-overfeat "fully-connected-inference-overfeat-test")
set_tests_properties(fully-connected-inference-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;685;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(fully-connected-inference-vgg "fully-connected-inference-vgg-test")
set_tests_properties(fully-connected-inference-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;691;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(fully-connected-output-smoketest "fully-connected-output-smoketest")
set_tests_properties(fully-connected-output-smoketest PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;698;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(fully-connected-output-alexnet "fully-connected-output-alexnet-test")
set_tests_properties(fully-connected-output-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;704;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(fully-connected-output-overfeat "fully-connected-output-overfeat-test")
set_tests_properties(fully-connected-output-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;710;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(fully-connected-output-vgg "fully-connected-output-vgg-test")
set_tests_properties(fully-connected-output-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;716;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(max-pooling-output-smoketest "max-pooling-output-smoketest")
set_tests_properties(max-pooling-output-smoketest PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;723;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(max-pooling-output-overfeat "max-pooling-output-overfeat-test")
set_tests_properties(max-pooling-output-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;729;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(max-pooling-output-vgg "max-pooling-output-vgg-test")
set_tests_properties(max-pooling-output-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;735;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(relu-output-alexnet "relu-output-alexnet-test")
set_tests_properties(relu-output-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;741;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(relu-output-overfeat "relu-output-overfeat-test")
set_tests_properties(relu-output-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;747;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(relu-output-vgg "relu-output-vgg-test")
set_tests_properties(relu-output-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;753;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(relu-input-gradient-alexnet "relu-input-gradient-alexnet-test")
set_tests_properties(relu-input-gradient-alexnet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;760;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(relu-input-gradient-overfeat "relu-input-gradient-overfeat-test")
set_tests_properties(relu-input-gradient-overfeat PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;766;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(relu-input-gradient-vgg "relu-input-gradient-vgg-test")
set_tests_properties(relu-input-gradient-vgg PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;772;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(softmax-output-smoketest "softmax-output-smoketest")
set_tests_properties(softmax-output-smoketest PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;779;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
add_test(softmax-output-imagenet "softmax-output-imagenet-test")
set_tests_properties(softmax-output-imagenet PROPERTIES  _BACKTRACE_TRIPLES "/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;785;ADD_TEST;/home/soniar/naiveDarknetNNPACKARMSVE/NNPACK/CMakeLists.txt;0;")
subdirs("deps/cpuinfo")
subdirs("deps/pthreadpool")
subdirs("deps/psimd")
subdirs("deps/fp16")
subdirs("deps/googletest")
